//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinalProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EVENT
    {
        public int ID_Event { get; set; }
        public string Nama_Event { get; set; }
        public Nullable<System.DateTime> Tanggal_Mulai { get; set; }
        public Nullable<System.DateTime> Tanggal_Selesai { get; set; }
        public string Lokasi_Event { get; set; }
        public string Latitude_event { get; set; }
        public string Longitude_event { get; set; }
    }
}
