//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinalProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class REKOMENDASI
    {
        public int ID_Rekomendasi { get; set; }
        public string Nama_Wisata_Rekomendasi { get; set; }
        public string Alamat_Wisata_Rekomendasi { get; set; }
        public string Telpon_Wisata_Rekomendasi { get; set; }
        public string Latitude_Wisata_Rekomendasi { get; set; }
        public string Longitude_Wisata_Rekomendasi { get; set; }
    }
}
