//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinalProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class REKREASI
    {
        public int ID_Rekreasi { get; set; }
        public Nullable<int> ID_Kategori_Rekreasi { get; set; }
        public string Nama_Rekreasi { get; set; }
        public string Alamat_Rekreasi { get; set; }
        public string Telpon_Rekreasi { get; set; }
        public byte[] Foto_Rekreasi { get; set; }
        public string Latitude_Rekreasi { get; set; }
        public string Longitude_Rekreasi { get; set; }
    
        public virtual KATEGORI_REKREASI KATEGORI_REKREASI { get; set; }
    }
}
