//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinalProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RESTORAN
    {
        public int ID_Restoran { get; set; }
        public int ID_Kategori_Restoran { get; set; }
        public string Nama_Restoran { get; set; }
        public string Alamat_Restoran { get; set; }
        public string Telpon_Restoran { get; set; }
        public byte[] Foto_Restoran { get; set; }
        public string Latitude_Restoran { get; set; }
        public string Longitude_Restoran { get; set; }
    
        public virtual KATEGORI_RESTORAN KATEGORI_RESTORAN { get; set; }
    }
}
