//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinalProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TRANSPORTASI
    {
        public int ID_Transportasi { get; set; }
        public string Nama_Transportasi { get; set; }
        public string Rute_Asal { get; set; }
        public string Rute_Tujuan { get; set; }
        public decimal Price { get; set; }
        public int ID_Kategori_Transportasi { get; set; }
    
        public virtual KATEGORI_TRASPORTASI KATEGORI_TRASPORTASI { get; set; }
    }
}
