//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinalProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WISATA
    {
        public int ID_Wisata { get; set; }
        public int ID_Kategori_Wisata { get; set; }
        public string Nama_Wisata { get; set; }
        public string Alamat_Wisata { get; set; }
        public string Telpon_Wisata { get; set; }
        public byte[] Foto_Wisata { get; set; }
        public string Deskripsi_Wisata { get; set; }
        public string Latitude_Wisata { get; set; }
        public string Longitude_Wisata { get; set; }
    
        public virtual KATEGORI_WISATA KATEGORI_WISATA { get; set; }
    }
}
