USE [master]
GO

/****** Object:  Database [SHEMO]    Script Date: 6/14/2014 8:10:38 PM ******/
CREATE DATABASE [SHEMO]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'SHEMO', FILENAME = N'C:\Users\enelde\AppData\Local\Microsoft\Microsoft SQL Server Local DB\Instances\v11.0\SHEMO.mdf' , SIZE = 3136KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'SHEMO_log', FILENAME = N'C:\Users\enelde\AppData\Local\Microsoft\Microsoft SQL Server Local DB\Instances\v11.0\SHEMO.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [SHEMO] SET COMPATIBILITY_LEVEL = 110
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [SHEMO].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [SHEMO] SET ANSI_NULL_DEFAULT ON 
GO

ALTER DATABASE [SHEMO] SET ANSI_NULLS ON 
GO

ALTER DATABASE [SHEMO] SET ANSI_PADDING ON 
GO

ALTER DATABASE [SHEMO] SET ANSI_WARNINGS ON 
GO

ALTER DATABASE [SHEMO] SET ARITHABORT ON 
GO

ALTER DATABASE [SHEMO] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [SHEMO] SET AUTO_CREATE_STATISTICS ON 
GO

ALTER DATABASE [SHEMO] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [SHEMO] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [SHEMO] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [SHEMO] SET CURSOR_DEFAULT  LOCAL 
GO

ALTER DATABASE [SHEMO] SET CONCAT_NULL_YIELDS_NULL ON 
GO

ALTER DATABASE [SHEMO] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [SHEMO] SET QUOTED_IDENTIFIER ON 
GO

ALTER DATABASE [SHEMO] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [SHEMO] SET  DISABLE_BROKER 
GO

ALTER DATABASE [SHEMO] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [SHEMO] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [SHEMO] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [SHEMO] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [SHEMO] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [SHEMO] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [SHEMO] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [SHEMO] SET RECOVERY FULL 
GO

ALTER DATABASE [SHEMO] SET  MULTI_USER 
GO

ALTER DATABASE [SHEMO] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [SHEMO] SET DB_CHAINING OFF 
GO

ALTER DATABASE [SHEMO] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [SHEMO] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [SHEMO] SET  READ_WRITE 
GO

