//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinalProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class KATEGORI_RESTORAN
    {
        public KATEGORI_RESTORAN()
        {
            this.RESTORANs = new HashSet<RESTORAN>();
        }
    
        public int ID_Kategori_Restoran { get; set; }
        public string Kategori_Restoran1 { get; set; }
    
        public virtual ICollection<RESTORAN> RESTORANs { get; set; }
    }
}
