//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinalProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class KATEGORI_TRASPORTASI
    {
        public KATEGORI_TRASPORTASI()
        {
            this.TRANSPORTASIs = new HashSet<TRANSPORTASI>();
        }
    
        public int ID_Kategori_Transportasi { get; set; }
        public string Kategori_Transportasi { get; set; }
    
        public virtual ICollection<TRANSPORTASI> TRANSPORTASIs { get; set; }
    }
}
