//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinalProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PROFILE
    {
        public int ID_Profile { get; set; }
        public string Nama_Profile { get; set; }
        public byte[] Foto_Profile { get; set; }
        public string Deskripsi_Profile { get; set; }
    }
}
