//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinalProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TAKSI
    {
        public int ID_Taksi { get; set; }
        public string Nama_Taksi { get; set; }
        public string Telpon_Taksi { get; set; }
        public Nullable<decimal> Minimum_Price { get; set; }
    }
}
